# Generated by Django 4.0.4 on 2022-07-07 22:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thesite', '0010_addressprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddressProfile',
            new_name='Place',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='Optional_Address',
            new_name='address',
        ),
    ]
