# Generated by Django 4.0.4 on 2022-07-07 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thesite', '0011_rename_addressprofile_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
