# Generated by Django 4.0.4 on 2022-07-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesite', '0014_place_delete_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='city',
        ),
        migrations.RemoveField(
            model_name='place',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='place',
            name='country',
        ),
        migrations.RemoveField(
            model_name='place',
            name='image',
        ),
        migrations.RemoveField(
            model_name='place',
            name='referral',
        ),
        migrations.RemoveField(
            model_name='place',
            name='state',
        ),
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
