# Generated by Django 4.0.4 on 2022-07-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesite', '0016_place_name_alter_place_address_alter_place_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='place',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
